<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Publisher WebApp</title>
    <link href="css/style.css" type="text/css" rel="stylesheet">
</head>
<body onload=getImgWidth()>
    <a href="/"><img id="banner" src="img/logo.gif"></a>
    <div id="content">
        <div id="menu_static">
            <ul>
                <a href="list-news-items"><li>List news item</li></a>
                <a href="create-news-item"><li>Create news item</li></a>
                <a href="listUsers.do"><li>Account administration</li></a>
                <a href="logout"><li>Logout</li></a>
            </ul>
        </div>
        <div id="dynamic">
            <div id="menu_dynamic">